version: "3.8"
services:  
  docker-angular1:
    build: ./
    tty: true
    stdin_open: true
    ports:
      - 4200:4200
    volumes:
      - ./:/docker-angular1
      - /node_modules
    #command: npm start
    command: sh -c "tmux new -d -s my_session;
      tmux send-keys -t my_session npm Space start C-m;
      tmux attach -t my_session"